// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// anagram_get
CharacterVector anagram_get(String word, DataFrame words_internal);
RcppExport SEXP _anagram_anagram_get(SEXP wordSEXP, SEXP words_internalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type word(wordSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type words_internal(words_internalSEXP);
    rcpp_result_gen = Rcpp::wrap(anagram_get(word, words_internal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_anagram_anagram_get", (DL_FUNC) &_anagram_anagram_get, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_anagram(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
