# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_all_anagrams <- function(grouped, n) {
    .Call(`_anagram_get_all_anagrams`, grouped, n)
}

